
const S = {
  page: {
    minHeight: "100vh",
    background: "var(--bg-primary)",
    padding: "32px 18px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  card: {
    width: "100%",
    maxWidth: "720px",
    background: "var(--bg-secondary)",
    border: "1px solid var(--border-color)",
    borderRadius: "24px",
    padding: "34px",
    boxShadow: "0 20px 60px rgba(15,23,42,0.12)",
    animation: "fadeUp 0.45s ease both",
    position: "relative",
    overflow: "hidden",
  },
  icon: {
    fontSize: "54px",
    width: "76px",
    height: "76px",
    borderRadius: "22px",
    background: "var(--surface-alt)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: "18px",
    animation: "bounceSoft 2.4s ease-in-out infinite",
  },
  eyebrow: {
    margin: 0,
    color: "var(--button-primary)",
    fontSize: "12px",
    fontWeight: 800,
    letterSpacing: "0.08em",
    textTransform: "uppercase",
  },
  code: {
    margin: "8px 0 0",
    color: "var(--text-primary)",
    fontSize: "58px",
    lineHeight: 1,
    fontWeight: 900,
  },
  title: {
    margin: "12px 0 0",
    color: "var(--text-primary)",
    fontSize: "26px",
    lineHeight: 1.25,
  },
  body: {
    margin: "12px 0 22px",
    color: "var(--text-secondary)",
    fontSize: "15px",
    lineHeight: 1.7,
  },
  actions: {
    display: "flex",
    gap: "10px",
    flexWrap: "wrap",
    marginTop: "18px",
  },
  primaryButton: {
    border: "none",
    borderRadius: "12px",
    padding: "12px 18px",
    background: "var(--button-primary)",
    color: "white",
    fontWeight: 800,
    cursor: "pointer",
  },
  secondaryButton: {
    border: "1px solid var(--border-color)",
    borderRadius: "12px",
    padding: "12px 18px",
    background: "var(--bg-secondary)",
    color: "var(--text-primary)",
    fontWeight: 800,
    cursor: "pointer",
  },
};

export default S;
